version: 2

build:
  jobs:
    pre_build:
      - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ _build/linkcheck
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

formats: all

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
