name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 06:00 UTC

jobs:

  build:

    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          create-args: python=${{ matrix.python-version }}
          environment-file: environments/tests/env-ci.yml
          post-cleanup: none

      - name: Install OSMnx
        run: |
          pip install -e .
          conda list
          conda info --all

      - name: Lint code
        run: |
          black . --line-length 100 --check --diff
          ruff check .

      - name: Test docs
        run: |
          make -C ./docs html
          python -m sphinx -b linkcheck docs/ docs/_build/linkcheck

      - name: Test code
        run: |
          coverage run --source ./osmnx --module pytest --verbose
          coverage xml -i
          coverage report -m

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
