name: Test minimal versions

on:
  schedule:
    - cron: '0 7 * * 1' # Every Monday at 07:00 UTC
  workflow_dispatch:

jobs:

  build:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          environment-file: environments/tests/env-test-minimal.yml
          post-cleanup: none

      - name: Install OSMnx
        run: |
          pip install -e .
          conda list
          conda info --all

      - name: Lint code
        run: |
          SKIP=no-commit-to-branch pre-commit run --all-files
          hatch build --clean
          twine check --strict ./dist/*

      - name: Test code
        run: pytest --cov=./osmnx --cov-report=xml --cov-report=term-missing --verbose

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
