name: Test minimal versions

on:
  schedule:
    - cron: '0 7 * * 1' # Every Monday at 07:00 UTC
  workflow_dispatch:

jobs:

  build:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          environment-file: environments/tests/env-test-minimal.yml
          post-cleanup: none

      - name: Install OSMnx
        run: |
          pip install -e .
          conda list
          conda info --all

      - name: Lint code
        run: |
          black . --check --verbose
          ruff check . --verbose

      - name: Test docs
        run: |
          make -C ./docs html
          python -m sphinx -b linkcheck docs/ docs/_build/linkcheck

      - name: Test code
        run: |
          coverage run --source ./osmnx --module pytest --verbose
          coverage xml -i
          coverage report -m

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
